/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 30
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 33
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_SEMI = 2,
  sym_doc_comment = 3,
  sym_line_comment = 4,
  anon_sym_SLASH_STAR = 5,
  anon_sym_STAR_SLASH = 6,
  aux_sym_comment_text_token1 = 7,
  sym_text_literal = 8,
  sym_char_literal = 9,
  sym_float_literal = 10,
  sym_int_literal = 11,
  sym_hex_literal = 12,
  anon_sym_true = 13,
  anon_sym_false = 14,
  sym_null_literal = 15,
  anon_sym_let = 16,
  anon_sym_EQ = 17,
  anon_sym_else = 18,
  sym_source_file = 19,
  sym_block_comment = 20,
  sym_comment_text = 21,
  sym_bool_literal = 22,
  sym__literal = 23,
  sym__dec = 24,
  sym_let_dec = 25,
  sym_let_else_dec = 26,
  sym__exp = 27,
  sym_var_exp = 28,
  sym__pat = 29,
  sym_var_pat = 30,
  aux_sym_source_file_repeat1 = 31,
  aux_sym_comment_text_repeat1 = 32,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_SEMI] = ";",
  [sym_doc_comment] = "doc_comment",
  [sym_line_comment] = "line_comment",
  [anon_sym_SLASH_STAR] = "/*",
  [anon_sym_STAR_SLASH] = "*/",
  [aux_sym_comment_text_token1] = "comment_text_token1",
  [sym_text_literal] = "text_literal",
  [sym_char_literal] = "char_literal",
  [sym_float_literal] = "float_literal",
  [sym_int_literal] = "int_literal",
  [sym_hex_literal] = "hex_literal",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_null_literal] = "null_literal",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_else] = "else",
  [sym_source_file] = "source_file",
  [sym_block_comment] = "block_comment",
  [sym_comment_text] = "comment_text",
  [sym_bool_literal] = "bool_literal",
  [sym__literal] = "_literal",
  [sym__dec] = "_dec",
  [sym_let_dec] = "let_dec",
  [sym_let_else_dec] = "let_else_dec",
  [sym__exp] = "_exp",
  [sym_var_exp] = "var_exp",
  [sym__pat] = "_pat",
  [sym_var_pat] = "var_pat",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_comment_text_repeat1] = "comment_text_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_doc_comment] = sym_doc_comment,
  [sym_line_comment] = sym_line_comment,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [anon_sym_STAR_SLASH] = anon_sym_STAR_SLASH,
  [aux_sym_comment_text_token1] = aux_sym_comment_text_token1,
  [sym_text_literal] = sym_text_literal,
  [sym_char_literal] = sym_char_literal,
  [sym_float_literal] = sym_float_literal,
  [sym_int_literal] = sym_int_literal,
  [sym_hex_literal] = sym_hex_literal,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_null_literal] = sym_null_literal,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_else] = anon_sym_else,
  [sym_source_file] = sym_source_file,
  [sym_block_comment] = sym_block_comment,
  [sym_comment_text] = sym_comment_text,
  [sym_bool_literal] = sym_bool_literal,
  [sym__literal] = sym__literal,
  [sym__dec] = sym__dec,
  [sym_let_dec] = sym_let_dec,
  [sym_let_else_dec] = sym_let_else_dec,
  [sym__exp] = sym__exp,
  [sym_var_exp] = sym_var_exp,
  [sym__pat] = sym__pat,
  [sym_var_pat] = sym_var_pat,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_comment_text_repeat1] = aux_sym_comment_text_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_doc_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_text_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_text_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_char_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_float_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_int_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_hex_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_null_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_text] = {
    .visible = true,
    .named = true,
  },
  [sym_bool_literal] = {
    .visible = true,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [sym__dec] = {
    .visible = false,
    .named = true,
  },
  [sym_let_dec] = {
    .visible = true,
    .named = true,
  },
  [sym_let_else_dec] = {
    .visible = true,
    .named = true,
  },
  [sym__exp] = {
    .visible = false,
    .named = true,
  },
  [sym_var_exp] = {
    .visible = true,
    .named = true,
  },
  [sym__pat] = {
    .visible = false,
    .named = true,
  },
  [sym_var_pat] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_text_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '"', 1,
        '\'', 3,
        '*', 8,
        '/', 6,
        '0', 30,
        ';', 13,
        '=', 34,
        '_', 23,
        '+', 9,
        '-', 9,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(31);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(25);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(26);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(27);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(27);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(28);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(17);
      if (lookahead == '/') ADVANCE(15);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(22);
      if (lookahead == '/') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(18);
      END_STATE();
    case 9:
      if (lookahead == '0') ADVANCE(30);
      if (lookahead == '_') ADVANCE(32);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(33);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_doc_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead == '/') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_STAR_SLASH);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_comment_text_token1);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_comment_text_token1);
      if (lookahead == '*') ADVANCE(17);
      if (lookahead == '/') ADVANCE(15);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_comment_text_token1);
      if (lookahead == '*') ADVANCE(22);
      if (lookahead == '/') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_comment_text_token1);
      if (lookahead == '/') ADVANCE(18);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_text_literal);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_text_literal);
      if (lookahead == '"') ADVANCE(25);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_char_literal);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_char_literal);
      if (lookahead == '\'') ADVANCE(27);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_float_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_int_literal);
      if (lookahead == '.') ADVANCE(10);
      if (lookahead == '_') ADVANCE(32);
      if (lookahead == 'x') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_int_literal);
      if (lookahead == '.') ADVANCE(10);
      if (lookahead == '_') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_int_literal);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_hex_literal);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'e') ADVANCE(1);
      if (lookahead == 'f') ADVANCE(2);
      if (lookahead == 'l') ADVANCE(3);
      if (lookahead == 'n') ADVANCE(4);
      if (lookahead == 't') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'l') ADVANCE(6);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(7);
      END_STATE();
    case 3:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == 'u') ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == 'r') ADVANCE(10);
      END_STATE();
    case 6:
      if (lookahead == 's') ADVANCE(11);
      END_STATE();
    case 7:
      if (lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 8:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 9:
      if (lookahead == 'l') ADVANCE(14);
      END_STATE();
    case 10:
      if (lookahead == 'u') ADVANCE(15);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 12:
      if (lookahead == 's') ADVANCE(17);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 14:
      if (lookahead == 'l') ADVANCE(18);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_null_literal);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 7},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 7},
  [15] = {.lex_state = 7},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 7},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {(TSStateId)(-1),},
  [29] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_block_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym_doc_comment] = ACTIONS(3),
    [sym_line_comment] = ACTIONS(5),
    [anon_sym_SLASH_STAR] = ACTIONS(7),
    [anon_sym_STAR_SLASH] = ACTIONS(1),
    [sym_text_literal] = ACTIONS(1),
    [sym_char_literal] = ACTIONS(1),
    [sym_float_literal] = ACTIONS(1),
    [sym_int_literal] = ACTIONS(1),
    [sym_hex_literal] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_null_literal] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(22),
    [sym_block_comment] = STATE(1),
    [sym_bool_literal] = STATE(8),
    [sym__literal] = STATE(11),
    [sym__dec] = STATE(18),
    [sym_let_dec] = STATE(13),
    [sym_let_else_dec] = STATE(17),
    [sym__exp] = STATE(17),
    [sym_var_exp] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(9),
    [sym_identifier] = ACTIONS(11),
    [sym_doc_comment] = ACTIONS(3),
    [sym_line_comment] = ACTIONS(5),
    [anon_sym_SLASH_STAR] = ACTIONS(7),
    [sym_text_literal] = ACTIONS(13),
    [sym_char_literal] = ACTIONS(13),
    [sym_float_literal] = ACTIONS(13),
    [sym_int_literal] = ACTIONS(15),
    [sym_hex_literal] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_null_literal] = ACTIONS(15),
    [anon_sym_let] = ACTIONS(19),
  },
  [STATE(2)] = {
    [sym_block_comment] = STATE(2),
    [sym_bool_literal] = STATE(8),
    [sym__literal] = STATE(11),
    [sym__dec] = STATE(20),
    [sym_let_dec] = STATE(13),
    [sym_let_else_dec] = STATE(17),
    [sym__exp] = STATE(17),
    [sym_var_exp] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(21),
    [sym_identifier] = ACTIONS(11),
    [sym_doc_comment] = ACTIONS(3),
    [sym_line_comment] = ACTIONS(5),
    [anon_sym_SLASH_STAR] = ACTIONS(7),
    [sym_text_literal] = ACTIONS(13),
    [sym_char_literal] = ACTIONS(13),
    [sym_float_literal] = ACTIONS(13),
    [sym_int_literal] = ACTIONS(15),
    [sym_hex_literal] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_null_literal] = ACTIONS(15),
    [anon_sym_let] = ACTIONS(19),
  },
  [STATE(3)] = {
    [sym_block_comment] = STATE(3),
    [sym_bool_literal] = STATE(8),
    [sym__literal] = STATE(11),
    [sym__dec] = STATE(27),
    [sym_let_dec] = STATE(13),
    [sym_let_else_dec] = STATE(17),
    [sym__exp] = STATE(17),
    [sym_var_exp] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym_identifier] = ACTIONS(25),
    [sym_doc_comment] = ACTIONS(3),
    [sym_line_comment] = ACTIONS(5),
    [anon_sym_SLASH_STAR] = ACTIONS(7),
    [sym_text_literal] = ACTIONS(28),
    [sym_char_literal] = ACTIONS(28),
    [sym_float_literal] = ACTIONS(28),
    [sym_int_literal] = ACTIONS(31),
    [sym_hex_literal] = ACTIONS(28),
    [anon_sym_true] = ACTIONS(34),
    [anon_sym_false] = ACTIONS(34),
    [sym_null_literal] = ACTIONS(31),
    [anon_sym_let] = ACTIONS(37),
  },
  [STATE(4)] = {
    [sym_block_comment] = STATE(4),
    [sym_bool_literal] = STATE(8),
    [sym__literal] = STATE(11),
    [sym__exp] = STATE(16),
    [sym_var_exp] = STATE(11),
    [sym_identifier] = ACTIONS(11),
    [sym_doc_comment] = ACTIONS(3),
    [sym_line_comment] = ACTIONS(5),
    [anon_sym_SLASH_STAR] = ACTIONS(7),
    [sym_text_literal] = ACTIONS(13),
    [sym_char_literal] = ACTIONS(13),
    [sym_float_literal] = ACTIONS(13),
    [sym_int_literal] = ACTIONS(15),
    [sym_hex_literal] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_null_literal] = ACTIONS(15),
  },
  [STATE(5)] = {
    [sym_block_comment] = STATE(5),
    [sym_bool_literal] = STATE(8),
    [sym__literal] = STATE(11),
    [sym__exp] = STATE(21),
    [sym_var_exp] = STATE(11),
    [sym_identifier] = ACTIONS(11),
    [sym_doc_comment] = ACTIONS(3),
    [sym_line_comment] = ACTIONS(5),
    [anon_sym_SLASH_STAR] = ACTIONS(7),
    [sym_text_literal] = ACTIONS(13),
    [sym_char_literal] = ACTIONS(13),
    [sym_float_literal] = ACTIONS(13),
    [sym_int_literal] = ACTIONS(15),
    [sym_hex_literal] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_null_literal] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(7), 1,
      anon_sym_SLASH_STAR,
    STATE(6), 1,
      sym_block_comment,
    ACTIONS(23), 5,
      ts_builtin_sym_end,
      sym_text_literal,
      sym_char_literal,
      sym_float_literal,
      sym_hex_literal,
    ACTIONS(40), 6,
      sym_identifier,
      sym_int_literal,
      anon_sym_true,
      anon_sym_false,
      sym_null_literal,
      anon_sym_let,
  [28] = 7,
    ACTIONS(42), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(44), 1,
      anon_sym_STAR_SLASH,
    ACTIONS(46), 1,
      aux_sym_comment_text_token1,
    STATE(7), 1,
      sym_block_comment,
    STATE(14), 1,
      aux_sym_comment_text_repeat1,
    STATE(25), 1,
      sym_comment_text,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_line_comment,
  [51] = 5,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(7), 1,
      anon_sym_SLASH_STAR,
    STATE(8), 1,
      sym_block_comment,
    ACTIONS(48), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_else,
  [69] = 5,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(7), 1,
      anon_sym_SLASH_STAR,
    STATE(9), 1,
      sym_block_comment,
    ACTIONS(50), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_else,
  [87] = 7,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(7), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(52), 1,
      sym_identifier,
    STATE(10), 1,
      sym_block_comment,
    STATE(23), 1,
      sym__pat,
    STATE(26), 1,
      sym_var_pat,
  [109] = 5,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(7), 1,
      anon_sym_SLASH_STAR,
    STATE(11), 1,
      sym_block_comment,
    ACTIONS(54), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_else,
  [127] = 5,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(7), 1,
      anon_sym_SLASH_STAR,
    STATE(12), 1,
      sym_block_comment,
    ACTIONS(56), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_else,
  [145] = 6,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(7), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(60), 1,
      anon_sym_else,
    STATE(13), 1,
      sym_block_comment,
    ACTIONS(58), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [165] = 6,
    ACTIONS(42), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(46), 1,
      aux_sym_comment_text_token1,
    ACTIONS(62), 1,
      anon_sym_STAR_SLASH,
    STATE(14), 1,
      sym_block_comment,
    STATE(15), 1,
      aux_sym_comment_text_repeat1,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_line_comment,
  [185] = 5,
    ACTIONS(42), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(64), 1,
      anon_sym_STAR_SLASH,
    ACTIONS(66), 1,
      aux_sym_comment_text_token1,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_line_comment,
    STATE(15), 2,
      sym_block_comment,
      aux_sym_comment_text_repeat1,
  [203] = 5,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(7), 1,
      anon_sym_SLASH_STAR,
    STATE(16), 1,
      sym_block_comment,
    ACTIONS(69), 3,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_else,
  [221] = 5,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(7), 1,
      anon_sym_SLASH_STAR,
    STATE(17), 1,
      sym_block_comment,
    ACTIONS(58), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [238] = 6,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(7), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(71), 1,
      anon_sym_SEMI,
    STATE(18), 1,
      sym_block_comment,
  [257] = 4,
    ACTIONS(42), 1,
      anon_sym_SLASH_STAR,
    STATE(19), 1,
      sym_block_comment,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_line_comment,
    ACTIONS(73), 2,
      anon_sym_STAR_SLASH,
      aux_sym_comment_text_token1,
  [272] = 6,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(7), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(71), 1,
      anon_sym_SEMI,
    ACTIONS(75), 1,
      ts_builtin_sym_end,
    STATE(20), 1,
      sym_block_comment,
  [291] = 5,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(7), 1,
      anon_sym_SLASH_STAR,
    STATE(21), 1,
      sym_block_comment,
    ACTIONS(77), 2,
      ts_builtin_sym_end,
      anon_sym_SEMI,
  [308] = 5,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(7), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    STATE(22), 1,
      sym_block_comment,
  [324] = 5,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(7), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(81), 1,
      anon_sym_EQ,
    STATE(23), 1,
      sym_block_comment,
  [340] = 5,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(7), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(83), 1,
      anon_sym_EQ,
    STATE(24), 1,
      sym_block_comment,
  [356] = 5,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(7), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(85), 1,
      anon_sym_STAR_SLASH,
    STATE(25), 1,
      sym_block_comment,
  [372] = 5,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(7), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(87), 1,
      anon_sym_EQ,
    STATE(26), 1,
      sym_block_comment,
  [388] = 5,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(7), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(71), 1,
      anon_sym_SEMI,
    STATE(27), 1,
      sym_block_comment,
  [404] = 1,
    ACTIONS(89), 1,
      ts_builtin_sym_end,
  [408] = 1,
    ACTIONS(91), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 28,
  [SMALL_STATE(8)] = 51,
  [SMALL_STATE(9)] = 69,
  [SMALL_STATE(10)] = 87,
  [SMALL_STATE(11)] = 109,
  [SMALL_STATE(12)] = 127,
  [SMALL_STATE(13)] = 145,
  [SMALL_STATE(14)] = 165,
  [SMALL_STATE(15)] = 185,
  [SMALL_STATE(16)] = 203,
  [SMALL_STATE(17)] = 221,
  [SMALL_STATE(18)] = 238,
  [SMALL_STATE(19)] = 257,
  [SMALL_STATE(20)] = 272,
  [SMALL_STATE(21)] = 291,
  [SMALL_STATE(22)] = 308,
  [SMALL_STATE(23)] = 324,
  [SMALL_STATE(24)] = 340,
  [SMALL_STATE(25)] = 356,
  [SMALL_STATE(26)] = 372,
  [SMALL_STATE(27)] = 388,
  [SMALL_STATE(28)] = 404,
  [SMALL_STATE(29)] = 408,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [40] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__literal, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool_literal, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__exp, 1, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_exp, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__dec, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_text, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_text_repeat1, 2, 0, 0),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_text_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_dec, 4, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_text_repeat1, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_else_dec, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_pat, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__pat, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_comment, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_comment, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_motoko(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "motoko",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
