/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 11
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 11
#define ALIAS_COUNT 0
#define TOKEN_COUNT 7
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_hello = 1,
  sym_line_comment = 2,
  sym_doc_comment = 3,
  anon_sym_SLASH_STAR = 4,
  anon_sym_STAR_SLASH = 5,
  aux_sym_comment_text_token1 = 6,
  sym_source_file = 7,
  sym_block_comment = 8,
  sym_comment_text = 9,
  aux_sym_comment_text_repeat1 = 10,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_hello] = "hello",
  [sym_line_comment] = "line_comment",
  [sym_doc_comment] = "doc_comment",
  [anon_sym_SLASH_STAR] = "/*",
  [anon_sym_STAR_SLASH] = "*/",
  [aux_sym_comment_text_token1] = "comment_text_token1",
  [sym_source_file] = "source_file",
  [sym_block_comment] = "block_comment",
  [sym_comment_text] = "comment_text",
  [aux_sym_comment_text_repeat1] = "comment_text_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_hello] = anon_sym_hello,
  [sym_line_comment] = sym_line_comment,
  [sym_doc_comment] = sym_doc_comment,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [anon_sym_STAR_SLASH] = anon_sym_STAR_SLASH,
  [aux_sym_comment_text_token1] = aux_sym_comment_text_token1,
  [sym_source_file] = sym_source_file,
  [sym_block_comment] = sym_block_comment,
  [sym_comment_text] = sym_comment_text,
  [aux_sym_comment_text_repeat1] = aux_sym_comment_text_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_hello] = {
    .visible = true,
    .named = false,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_doc_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_text_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_comment_text_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '/') ADVANCE(1);
      if (lookahead == 'h') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '*') ADVANCE(12);
      if (lookahead == '/') ADVANCE(10);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(17);
      if (lookahead == '/') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == 'l') ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_hello);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead == '/') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(11);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_STAR_SLASH);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_comment_text_token1);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_comment_text_token1);
      if (lookahead == '*') ADVANCE(12);
      if (lookahead == '/') ADVANCE(10);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_comment_text_token1);
      if (lookahead == '*') ADVANCE(17);
      if (lookahead == '/') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_comment_text_token1);
      if (lookahead == '/') ADVANCE(13);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {(TSStateId)(-1),},
  [10] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_block_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_hello] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_comment] = ACTIONS(5),
    [anon_sym_SLASH_STAR] = ACTIONS(7),
    [anon_sym_STAR_SLASH] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(7),
    [sym_block_comment] = STATE(1),
    [anon_sym_hello] = ACTIONS(9),
    [sym_line_comment] = ACTIONS(3),
    [sym_doc_comment] = ACTIONS(5),
    [anon_sym_SLASH_STAR] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym_block_comment] = STATE(2),
    [sym_comment_text] = STATE(8),
    [aux_sym_comment_text_repeat1] = STATE(3),
    [sym_line_comment] = ACTIONS(5),
    [sym_doc_comment] = ACTIONS(5),
    [anon_sym_SLASH_STAR] = ACTIONS(11),
    [anon_sym_STAR_SLASH] = ACTIONS(13),
    [aux_sym_comment_text_token1] = ACTIONS(15),
  },
  [STATE(3)] = {
    [sym_block_comment] = STATE(3),
    [aux_sym_comment_text_repeat1] = STATE(4),
    [sym_line_comment] = ACTIONS(5),
    [sym_doc_comment] = ACTIONS(5),
    [anon_sym_SLASH_STAR] = ACTIONS(11),
    [anon_sym_STAR_SLASH] = ACTIONS(17),
    [aux_sym_comment_text_token1] = ACTIONS(15),
  },
  [STATE(4)] = {
    [sym_block_comment] = STATE(4),
    [aux_sym_comment_text_repeat1] = STATE(4),
    [sym_line_comment] = ACTIONS(5),
    [sym_doc_comment] = ACTIONS(5),
    [anon_sym_SLASH_STAR] = ACTIONS(11),
    [anon_sym_STAR_SLASH] = ACTIONS(19),
    [aux_sym_comment_text_token1] = ACTIONS(21),
  },
  [STATE(5)] = {
    [sym_block_comment] = STATE(5),
    [sym_line_comment] = ACTIONS(5),
    [sym_doc_comment] = ACTIONS(5),
    [anon_sym_SLASH_STAR] = ACTIONS(11),
    [anon_sym_STAR_SLASH] = ACTIONS(24),
    [aux_sym_comment_text_token1] = ACTIONS(24),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_doc_comment,
    ACTIONS(7), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(26), 1,
      ts_builtin_sym_end,
    STATE(6), 1,
      sym_block_comment,
  [16] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_doc_comment,
    ACTIONS(7), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(28), 1,
      ts_builtin_sym_end,
    STATE(7), 1,
      sym_block_comment,
  [32] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_doc_comment,
    ACTIONS(7), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(30), 1,
      anon_sym_STAR_SLASH,
    STATE(8), 1,
      sym_block_comment,
  [48] = 1,
    ACTIONS(32), 1,
      ts_builtin_sym_end,
  [52] = 1,
    ACTIONS(34), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 16,
  [SMALL_STATE(8)] = 32,
  [SMALL_STATE(9)] = 48,
  [SMALL_STATE(10)] = 52,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_text, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_text_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_text_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [24] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_text_repeat1, 1, 0, 0),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [28] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_comment, 2, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_comment, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_motoko(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "motoko",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
